#!/usr/bin/env python3
"""Resolve a USB camera through libudev, then replace this process with usb_cam."""

from __future__ import annotations

import os
import sys
import time
from glob import glob
from pathlib import Path

import pyudev
from ament_index_python.packages import get_package_prefix


def matching_capture_devices(context: pyudev.Context) -> list[str]:
    by_id = sorted(set(str(Path(path).resolve()) for path in glob('/dev/v4l/by-id/*video-index0')))
    if by_id:
        return by_id

    matches = []
    for device in context.list_devices(subsystem='video4linux'):
        properties = device.properties
        if ':capture:' not in properties.get('ID_V4L_CAPABILITIES', ''):
            continue
        if device.device_node:
            matches.append(device)
    # A camera can expose capture and encoded-video interfaces. The primary
    # V4L2 interface sorts first and is the one usb_cam can decode.
    return [device.device_node for device in sorted(matches, key=lambda item: (
        item.properties.get('ID_USB_INTERFACE_NUM', 'ff'), item.sys_name))]


def resolve_device(timeout_s: float = 8.0) -> str:
    explicit = os.environ.get('POM_CAMERA_DEVICE', 'auto')
    if explicit != 'auto':
        resolved = str(Path(explicit).resolve())
        if not Path(resolved).exists():
            raise RuntimeError(f'Configured camera device does not exist: {explicit}')
        return resolved

    camera_index = int(os.environ.get('POM_CAMERA_INDEX', '0'))
    context = pyudev.Context()
    deadline = time.monotonic() + timeout_s
    while True:
        matches = matching_capture_devices(context)
        if len(matches) > camera_index:
            return matches[camera_index]
        if time.monotonic() >= deadline:
            raise RuntimeError(f'No V4L2 capture device found for camera index {camera_index}')
        time.sleep(0.25)


def main() -> None:
    try:
        device = resolve_device()
    except (KeyError, RuntimeError) as error:
        print(f'Camera discovery failed: {error}', file=sys.stderr, flush=True)
        raise SystemExit(2) from error

    executable = Path(get_package_prefix('usb_cam')) / 'lib' / 'usb_cam' / 'usb_cam_node_exe'
    print(f'Camera discovery selected {device} for camera index '
          f"{os.environ.get('POM_CAMERA_INDEX', '0')}", flush=True)
    # Parameters generated by the XML launch remain intact. This final
    # command-line parameter overrides its video_device value.
    os.execv(str(executable), [str(executable), *sys.argv[1:], '-p', f'video_device:={device}'])


if __name__ == '__main__':
    main()
